#!/bin/bash

echo "--------------"
echo "submitting job"

echo \$HOME is: $HOME


# qsub -q dev -l nodes=1:ppn=<cores>:<feature>
# qsub -q dev -l nodes=1:ppn=1:magny_cours test_submission

qsub -q test -l nodes=1:ppn=3:magny_cours,walltime=6:00:00 plink_vcf_batch -e $HOME/ClusterBAPR/output/ -o $HOME/ClusterBAPR/output/ >> qsub_outputs
# qsub -I ls -q shared nodes=1:ppn=2:magny_cours


tail qsub_outputs

# qsub -q dev -l nodes=1:ppn=1:magny_cours plink_vcf_batch -e ./results/ -o ./results/
# qsub -q dev -l nodes=1:ppn=1:magny_cours plink_vcf_batch
