#!/bin/bash

echo "submitting job"

echo $HOME

# ls -l > directory_listing
# cat directory_listing
# rm directory_listing

# qsub -q dev -l nodes=1:ppn=<cores>:<feature>
# qsub -q dev -l nodes=1:ppn=1:magny_cours test_submission

qsub -q dev -l nodes=1:ppn=1:magny_cours plink_vcf_batch -e $HOME/ClusterBAPR/output/ -o $HOME/ClusterBAPR/output/ >> qsub_outputs

tail qsub_outputs

# qsub -q dev -l nodes=1:ppn=1:magny_cours plink_vcf_batch -e ./results/ -o ./results/
# qsub -q dev -l nodes=1:ppn=1:magny_cours plink_vcf_batch
