#!/bin/bash

echo "--------------"
echo "submitting job"

echo \$HOME is: $HOME



qsub -q shared test_cluster -e $HOME/ClusterBAPR/output/ -o $HOME/ClusterBAPR/output/ >> qsub_outputs

tail qsub_outputs
# qsub test_cluster > qsub_outputs

# qsub -q shared -l nodes=1:ppn=3:magny_cours,walltime=1:00:00 test_cluster -e $HOME/ClusterBAPR/output/ -o $HOME/ClusterBAPR/output/ >> qsub_outputs
# qsub -q dev -l nodes=1:ppn=<cores>:<feature>
# qsub -q dev -l nodes=1:ppn=1:magny_cours test_submission
# qsub -q shared -l nodes=1:ppn=3:magny_cours,walltime=100:00:00 plink_vcf_batch -e $HOME/ClusterBAPR/output/ -o $HOME/ClusterBAPR/output/ >> qsub_outputs
# qsub -I ls -q shared nodes=1:ppn=2:magny_cours
# qsub -q dev -l nodes=1:ppn=1:magny_cours plink_vcf_batch -e ./results/ -o ./results/
# qsub -q dev -l nodes=1:ppn=1:magny_cours plink_vcf_batch
